name: Update Earth Engine Data

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - main
    paths:
      - 'scripts/update_metrics.py'

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        
    - name: Install dependencies
      run: |
        pip install earthengine-api pandas
        
    - name: Create credentials file
      env:
        EE_SERVICE_ACCOUNT_JSON: ${{ secrets.EE_SERVICE_ACCOUNT_JSON }}
      run: |
        echo "$EE_SERVICE_ACCOUNT_JSON" > /tmp/ee-credentials.json
        
    - name: Check credentials file (debug)
      run: |
        echo "Checking if credentials file exists..."
        ls -la /tmp/ee-credentials.json || echo "File not found!"
        echo "GOOGLE_APPLICATION_CREDENTIALS will be set to: /tmp/ee-credentials.json"
        
    - name: Run Earth Engine script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/ee-credentials.json
      run: python scripts/update_metrics.py
      
    - name: Remove credentials
      if: always()
      run: rm -f /tmp/ee-credentials.json
      
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update Earth Engine data - $(date +'%Y-%m-%d %H:%M:%S')" && git push)